/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jul.with.slf4j.logging;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {
    // SLF4J Logger
    private static final Logger logger = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) {
        // Log messages using SLF4J, which will be handled by Log4j2
        logger.info("This is an SLF4J info message.");
        logger.warn("This is an SLF4J warning message.");
    }
}
